projet-rails/config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
    get "search"
  end
  resources :pannes
  resources :modele_telephones
  resources :annonceurs
  resources :annonceurs
  resources :annonceurs
  resources :utilisateurs, :annonceur
  resources :search, :controllers => {search: 'search'}
  root 'home#index'
  resources :utilisateurs, :annonceur, :annonces

end

projet-rails/app/models/panne.rb
class Panne < ActiveRecord::Base
end

projet-rails/app/controllers/pannes_controller.rb
class PannesController < ApplicationController
  before_action :set_panne, only: [:show, :edit, :update, :destroy]

  # GET /pannes
  # GET /pannes.json
  def index
    @pannes = Panne.all
  end

  # GET /pannes/1
  # GET /pannes/1.json
  def show
  end

  # GET /pannes/new
  def new
    @panne = Panne.new
  end

  # GET /pannes/1/edit
  def edit
  end

  # POST /pannes
  # POST /pannes.json
  def create
    @panne = Panne.new(panne_params)

    respond_to do |format|
      if @panne.save
        format.html { redirect_to @panne, notice: 'Panne was successfully created.' }
        format.json { render :show, status: :created, location: @panne }
      else
        format.html { render :new }
        format.json { render json: @panne.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pannes/1
  # PATCH/PUT /pannes/1.json
  def update
    respond_to do |format|
      if @panne.update(panne_params)
        format.html { redirect_to @panne, notice: 'Panne was successfully updated.' }
        format.json { render :show, status: :ok, location: @panne }
      else
        format.html { render :edit }
        format.json { render json: @panne.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pannes/1
  # DELETE /pannes/1.json
  def destroy
    @panne.destroy
    respond_to do |format|
      format.html { redirect_to pannes_url, notice: 'Panne was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_panne
      @panne = Panne.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def panne_params
      params.require(:panne).permit(:nom, :description)
    end
end

projet-rails/app/helpers/pannes_helper.rb
module PannesHelper
end

projet-rails/app/views/pannes/_form.html.erb
<%= form_for(@panne) do |f| %>
  <% if @panne.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@panne.errors.count, "error") %> prohibited this panne from being saved:</h2>

      <ul>
      <% @panne.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projet-rails/app/views/pannes/edit.html.erb
<h1>Editing Panne</h1>

<%= render 'form' %>

<%= link_to 'Show', @panne %> |
<%= link_to 'Back', pannes_path %>

projet-rails/app/views/pannes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Pannes</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pannes.each do |panne| %>
      <tr>
        <td><%= panne.nom %></td>
        <td><%= panne.description %></td>
        <td><%= link_to 'Show', panne %></td>
        <td><%= link_to 'Edit', edit_panne_path(panne) %></td>
        <td><%= link_to 'Destroy', panne, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Panne', new_panne_path %>

projet-rails/app/views/pannes/new.html.erb
<h1>New Panne</h1>

<%= render 'form' %>

<%= link_to 'Back', pannes_path %>

projet-rails/app/views/pannes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @panne.nom %>
</p>

<p>
  <strong>Description:</strong>
  <%= @panne.description %>
</p>

<%= link_to 'Edit', edit_panne_path(@panne) %> |
<%= link_to 'Back', pannes_path %>