projet-rails/config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
    get "search"
  end
  resources :pannes
  resources :modele_telephones
  resources :annonceurs
  resources :annonceurs
  resources :annonceurs
  resources :utilisateurs, :annonceur
  resources :search, :controllers => {search: 'search'}
  root 'home#index'
  resources :utilisateurs, :annonceur, :annonces

end

projet-rails/app/models/modele_telephone.rb
class ModeleTelephone < ActiveRecord::Base
end

projet-rails/app/controllers/modele_telephones_controller.rb
class ModeleTelephonesController < ApplicationController
  before_action :set_modele_telephone, only: [:show, :edit, :update, :destroy]

  # GET /modele_telephones
  # GET /modele_telephones.json
  def index
    @modele_telephones = ModeleTelephone.all
  end

  # GET /modele_telephones/1
  # GET /modele_telephones/1.json
  def show
  end

  # GET /modele_telephones/new
  def new
    @modele_telephone = ModeleTelephone.new
  end

  # GET /modele_telephones/1/edit
  def edit
  end

  # POST /modele_telephones
  # POST /modele_telephones.json
  def create
    @modele_telephone = ModeleTelephone.new(modele_telephone_params)

    respond_to do |format|
      if @modele_telephone.save
        format.html { redirect_to @modele_telephone, notice: 'Modele telephone was successfully created.' }
        format.json { render :show, status: :created, location: @modele_telephone }
      else
        format.html { render :new }
        format.json { render json: @modele_telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /modele_telephones/1
  # PATCH/PUT /modele_telephones/1.json
  def update
    respond_to do |format|
      if @modele_telephone.update(modele_telephone_params)
        format.html { redirect_to @modele_telephone, notice: 'Modele telephone was successfully updated.' }
        format.json { render :show, status: :ok, location: @modele_telephone }
      else
        format.html { render :edit }
        format.json { render json: @modele_telephone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /modele_telephones/1
  # DELETE /modele_telephones/1.json
  def destroy
    @modele_telephone.destroy
    respond_to do |format|
      format.html { redirect_to modele_telephones_url, notice: 'Modele telephone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_modele_telephone
      @modele_telephone = ModeleTelephone.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def modele_telephone_params
      params.require(:modele_telephone).permit(:nom)
    end
end

projet-rails/app/helpers/modele_telephones_helper.rb
module ModeleTelephonesHelper
end

projet-rails/app/views/modele_telephones/_form.html.erb
<%= form_for(@modele_telephone) do |f| %>
  <% if @modele_telephone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@modele_telephone.errors.count, "error") %> prohibited this modele_telephone from being saved:</h2>

      <ul>
      <% @modele_telephone.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom %><br>
    <%= f.text_field :nom %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projet-rails/app/views/modele_telephones/edit.html.erb
<h1>Editing Modele Telephone</h1>

<%= render 'form' %>

<%= link_to 'Show', @modele_telephone %> |
<%= link_to 'Back', modele_telephones_path %>

projet-rails/app/views/modele_telephones/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Modele Telephones</h1>

<table>
  <thead>
    <tr>
      <th>Nom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @modele_telephones.each do |modele_telephone| %>
      <tr>
        <td><%= modele_telephone.nom %></td>
        <td><%= link_to 'Show', modele_telephone %></td>
        <td><%= link_to 'Edit', edit_modele_telephone_path(modele_telephone) %></td>
        <td><%= link_to 'Destroy', modele_telephone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Modele telephone', new_modele_telephone_path %>

projet-rails/app/views/modele_telephones/new.html.erb
<h1>New Modele Telephone</h1>

<%= render 'form' %>

<%= link_to 'Back', modele_telephones_path %>

projet-rails/app/views/modele_telephones/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nom:</strong>
  <%= @modele_telephone.nom %>
</p>

<%= link_to 'Edit', edit_modele_telephone_path(@modele_telephone) %> |
<%= link_to 'Back', modele_telephones_path %>