projet-rails/config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
    get "search"
  end
  resources :pannes
  resources :modele_telephones
  resources :annonceurs
  resources :annonceurs
  resources :annonceurs
  resources :utilisateurs, :annonceur
  resources :search, :controllers => {search: 'search'}
  root 'home#index'
  resources :utilisateurs, :annonceur, :annonces

end

projet-rails/app/models/reparation.rb
class Reparation < ActiveRecord::Base
end

projet-rails/app/controllers/reparations_controller.rb
class ReparationsController < ApplicationController
  before_action :set_reparation, only: [:show, :edit, :update, :destroy]

  # GET /reparations
  # GET /reparations.json
  def index
    @reparations = Reparation.all
  end

  # GET /reparations/1
  # GET /reparations/1.json
  def show
  end

  # GET /reparations/new
  def new
    @reparation = Reparation.new
  end

  # GET /reparations/1/edit
  def edit
  end

  # POST /reparations
  # POST /reparations.json
  def create
    @reparation = Reparation.new(reparation_params)

    respond_to do |format|
      if @reparation.save
        format.html { redirect_to @reparation, notice: 'Reparation was successfully created.' }
        format.json { render :show, status: :created, location: @reparation }
      else
        format.html { render :new }
        format.json { render json: @reparation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reparations/1
  # PATCH/PUT /reparations/1.json
  def update
    respond_to do |format|
      if @reparation.update(reparation_params)
        format.html { redirect_to @reparation, notice: 'Reparation was successfully updated.' }
        format.json { render :show, status: :ok, location: @reparation }
      else
        format.html { render :edit }
        format.json { render json: @reparation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reparations/1
  # DELETE /reparations/1.json
  def destroy
    @reparation.destroy
    respond_to do |format|
      format.html { redirect_to reparations_url, notice: 'Reparation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_reparation
      @reparation = Reparation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def reparation_params
      params.require(:reparation).permit(:name, :prix)
    end
end

projet-rails/app/helpers/reparations_helper.rb
module ReparationsHelper
end

projet-rails/app/views/reparations/_form.html.erb
<%= form_for(@reparation) do |f| %>
  <% if @reparation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reparation.errors.count, "error") %> prohibited this reparation from being saved:</h2>

      <ul>
      <% @reparation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <span>Annonce :</span>
    <textaera></textaera>
  </div>
  <div class="field">
    <span>reparation :</span>
    <label>Ecran</label>
    <input type="radio">
    <label>Batterie</label>
    <input type="radio">
    <label>Bouton power</label>
    <input type="radio">
    <label>Haut parleur</label>
    <input type="radio">
    <button>Add</button>
  </div>
  <div class="field">
    <span>Prix :</span>
    <input>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

projet-rails/app/views/reparations/edit.html.erb
<h1>Editing Reparation</h1>

<%= render 'form' %>

<%= link_to 'Show', @reparation %> |
<%= link_to 'Back', reparations_path %>

projet-rails/app/views/reparations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reparations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Prix</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reparations.each do |reparation| %>
      <tr>
        <td><%= reparation.name %></td>
        <td><%= reparation.prix %></td>
        <td><%= link_to 'Show', reparation %></td>
        <td><%= link_to 'Edit', edit_reparation_path(reparation) %></td>
        <td><%= link_to 'Destroy', reparation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Reparation', new_reparation_path %>

projet-rails/app/views/reparations/new.html.erb
<h1>New Reparation</h1>

<%= render 'form' %>

<%= link_to 'Back', reparations_path %>

projet-rails/app/views/reparations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @reparation.name %>
</p>

<p>
  <strong>Prix:</strong>
  <%= @reparation.prix %>
</p>

<%= link_to 'Edit', edit_reparation_path(@reparation) %> |
<%= link_to 'Back', reparations_path %>