projet-rails/config/routes.rb
Rails.application.routes.draw do
  resources :reparations
  devise_for :users, :controllers => { registrations: 'registrations' }
  resources :users do
    get "search"
  end
  resources :pannes
  resources :modele_telephones
  resources :annonceurs
  resources :annonceurs
  resources :annonceurs
  resources :utilisateurs, :annonceur
  resources :search, :controllers => {search: 'search'}
  root 'home#index'
  resources :utilisateurs, :annonceur, :annonces

end

projet-rails/app/models/annonceur.rb
class Annonceur < ActiveRecord::Base
	has_attached_file :image, styles: { small: "64x64", med: "100x100", large: "200x200" }

	validates_attachment_content_type :image, content_type: /\Aimage/
	validates_attachment_file_name :image, matches: [/png\Z/, /jpe?g\Z/, /gif\Z/]
	validates_with AttachmentSizeValidator,
		attributes: :image,
		less_than: 1.megabytes
	do_not_validate_attachment_file_type :image
end

projet-rails/app/controllers/annonceur_controller.rb
class AnnonceurController < ApplicationController
  def index
  end
end

projet-rails/app/controllers/annonceurs_controller.rb
class AnnonceursController < ApplicationController
  before_action :set_annonceur, only: [:show, :edit, :update, :destroy]

  # GET /annonceurs
  # GET /annonceurs.json
  def index
    @annonceurs = Annonceur.all
  end

  # GET /annonceurs/1
  # GET /annonceurs/1.json
  def show
  end

  # GET /annonceurs/new
  def new
    @annonceur = Annonceur.new
  end

  # GET /annonceurs/1/edit
  def edit
  end

  # POST /annonceurs
  # POST /annonceurs.json
  def create
    @annonceur = Annonceur.new(annonceur_params)

    respond_to do |format|
      if @annonceur.save
        format.html { redirect_to @annonceur, notice: 'Annonceur was successfully created.' }
        format.json { render :show, status: :created, location: @annonceur }
      else
        format.html { render :new }
        format.json { render json: @annonceur.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /annonceurs/1
  # PATCH/PUT /annonceurs/1.json
  def update
    respond_to do |format|
      if @annonceur.update(annonceur_params)
        format.html { redirect_to @annonceur, notice: 'Annonceur was successfully updated.' }
        format.json { render :show, status: :ok, location: @annonceur }
      else
        format.html { render :edit }
        format.json { render json: @annonceur.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /annonceurs/1
  # DELETE /annonceurs/1.json
  def destroy
    @annonceur.destroy
    respond_to do |format|
      format.html { redirect_to annonceurs_url, notice: 'Annonceur was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_annonceur
      @annonceur = Annonceur.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def annonceur_params
      params.require(:annonceur).permit(:email, :nom, :prenom, :password, :cp, :adresse, :telephone, :situation, :rayonIntervention, :image)
    end
end

projet-rails/app/helpers/annonceurs_helper.rb
module AnnonceursHelper
end

projet-rails/app/views/annonceurs/_form.html.erb
<div id="annonceur-form">
  <%= form_for(@annonceur) do |f| %>
    <% if @annonceur.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@annonceur.errors.count, "error") %> prohibited this annonceur from being saved:</h2>

        <ul>
        <% @annonceur.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <form class="form-horizontal">
      <div class="form-group">
        <label class="col-sm-4 control-label"><%= f.label :nom %></label>
        <div class="col-sm-8">
          <%= f.text_field :nom , class: 'form-control', placeholder: 'Nom'%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-4 control-label"><%= f.label :prenom %></label>
        <div class="col-sm-8">
          <%= f.text_field :prenom , class: 'form-control', placeholder: 'Prenom'%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-4 control-label"><%= f.label :cp %></label>
        <div class="col-sm-8">
          <%= f.text_field :cp , class: 'form-control', placeholder: 'Code postal'%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-4 control-label"><%= f.label :adresse %></label>
        <div class="col-sm-8">
          <%= f.text_field :adresse , class: 'form-control', placeholder: 'Adresse'%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-4 control-label"><%= f.label :telephone %></label>
        <div class="col-sm-8">
          <%= f.text_field :telephone , class: 'form-control', placeholder: 'Téléphone'%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-4 control-label"><%= f.label :situation %></label>
        <div class="col-sm-8">
          <%= f.text_field :situation , class: 'form-control', placeholder: 'Situation'%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-4 control-label"><%= f.label :rayonIntervention %></label>
        <div class="col-sm-8">
          <%= f.text_field :rayonIntervention , class: 'form-control', placeholder: 'Rayon d\'intervention'%>
        </div>
      </div>

      <div class="form-group">
        <label class="col-sm-4 control-label"><%= f.label :image %></label>
        <div class="col-sm-8">
          <%= f.file_field :image , class: 'form-control' %>
        </div>
      </div>

      <%= f.submit %>

    </form>

  <% end %>
</div>

projet-rails/app/views/annonceurs/edit.html.erb
<h1>Editing Annonceur</h1>

<%= render 'form' %>

<%= link_to 'Show', @annonceur %> |
<%= link_to 'Back', annonceurs_path %>

projet-rails/app/views/annonceurs/index.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Se déconnecter', destroy_user_session_path, method: :delete %>
<%= link_to 'Se connecter', new_user_session_path%>
<h1>Listing Annonceurs</h1>

<table class="table table-responsive">
  <thead>
    <tr>
      <th>Email</th>
      <th>Nom</th>
      <th>Prenom</th>
      <th>Password</th>
      <th>Cp</th>
      <th>Adresse</th>
      <th>Telephone</th>
      <th>Situation</th>
      <th>Rayonintervention</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @annonceurs.each do |annonceur| %>
      <tr>
        <td><%= annonceur.image.exists? ? image_tag(annonceur.image.url(:small)) : '&empty'.html_safe %></td>
        <!-- <td><%#= annonceur.email %></td> -->
        <td><%= annonceur.nom %></td>
        <td><%= annonceur.prenom %></td>
        <!-- <td><%#= annonceur.password %></td> -->
        <td><%= annonceur.cp %></td>
        <td><%= annonceur.adresse %></td>
        <td><%= annonceur.telephone %></td>
        <td><%= annonceur.situation %></td>
        <td><%= annonceur.rayonIntervention %></td>
        <td class="pull-right">
          <%= link_to annonceur , class: 'btn btn-sm btn-primary' do %>
            <i class="glyphicon glyphicon-search"> Show</i>
          <% end %>
        </td>
        <td class="pull-right">
          <%= link_to edit_annonceur_path(annonceur) , class: 'btn btn-sm btn-warning' do %>
            <i class="glyphicon glyphicon-pencil"> Edit</i>
          <% end %>
        </td>
        <td class="pull-right">
          <%= link_to annonceur, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-danger' do %>
            <i class="glyphicon glyphicon-remove"> Destroy</i>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to new_annonceur_path, class: 'btn btn-success' do %>
  <i class="glyphicon glyphicon-plus"> New Annonceur</i>
<% end %>

projet-rails/app/views/annonceurs/new.html.erb
<div class="inscription-annonceur">

<div class="page-header">
	<h1 class="center bold">S'inscrire</h1>
</div>

<%= render 'form' %>

<%= link_to 'Back', annonceurs_path %>
</div>

projet-rails/app/views/annonceurs/show.html.erb
<p id="notice"><%= notice %></p>

<div class="profil">
  <div class="page-profil">
    <%= image_tag("home.jpg", :alt => "home", :class => "image-profil") %>
    <h1>Fiche de <small><%= @annonceur.prenom %> <%= @annonceur.nom %></small></h1>
  </div>
  <div class=" affiche-profil">
    <div class="well">
      <% if @annonceur.image.exists? %>
        <%= image_tag @annonceur.image.url(:large) %>
      <% end %>
      <!-- <img src="http://lorempixel.com/200/200/people" alt="people" class="img-circle"> -->
      <h2><%= @annonceur.prenom %> <%= @annonceur.nom %></h2>
      <!-- <h4><i class="glyphicon glyphicon-envelope"></i> <%#= @annonceur.email %></h4> -->
      <h4><i class="glyphicon glyphicon-phone"></i> <%= @annonceur.telephone %></h4>
      <h4>
        <i class="glyphicon glyphicon-home"></i> <%= @annonceur.adresse %>
        <br>
        <%= @annonceur.cp %>
      </h4>
      <h4><i class="glyphicon glyphicon-user"></i> <%= @annonceur.situation %></h4>
      <h4><i class="glyphicon glyphicon-road"></i> <%= @annonceur.rayonIntervention %> km</h4>
    </div>
  </div>

  <%= link_to annonceurs_path do %>
    Retour
  <% end %>
</div>